name: CI

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: white-paper
        uses: w3c/spec-prod@v2
        with:
          SOURCE: white-paper/index.html
          DESTINATION: white-paper/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.WHITE_PAPER_ECHIDNA_TOKEN }}
          # Replace following with appropriate value. See options.md for details.
          W3C_WG_DECISION_URL: https://www.w3.org/2021/05/27-miniapp-minutes.html#t10
          W3C_BUILD_OVERRIDE: |
            specStatus: DNOTE
            shortName: mini-app-white-paper
